#!/bin/bash

# Lock file path
LOCKFILE=/tmp/color_picker.lock

# Create a lock file if it doesn't exist, or exit if it does
if [ -e "$LOCKFILE" ]; then
    echo "Script is already running. Exiting."
    exit 1
else
    touch "$LOCKFILE"
fi

# Function to remove the lock file upon script exit
cleanup() {
    rm -f "$LOCKFILE"
}
trap cleanup EXIT

TMPPCK=$(hyprpicker -a -n)
TMPPST=$(wl-paste)
CMD=$(echo "$TMPPST")
TMP=/tmp/xcolor_$CMD.png

hyprpick() {
    $TMPPCK
}

check_dependencies() {
    ! command -v hyprpicker &>/dev/null &&
        notify-send -u critical -a "Color Picker" xcolor-pick "gpick needs to be installed" && exit 1

    ! command -v magick &>/dev/null &&
        notify-send -u critical -a "Color Picker" xcolor-pick "imagemagick needs to be installed" && exit 1
}

main() {
    convert -size 120x120 xc:"$CMD" "$TMP"
    printf %s "$CMD" | wl-paste 

    notify-send -a "Color Picker" -i "$TMP" Color-picked! "$CMD"
}

check_dependencies
hyprpick
main

# Remove the lock file before exiting (cleanup function will handle this)
cleanup
