#!/bin/bash

# Define the location to store the PID
PID_FILE="$HOME/.config/hypr/scripts/wlsunset.pid"

# Check if the PID file exists and wlsunset is running
if [ -f "$PID_FILE" ] && pgrep -F "$PID_FILE" > /dev/null; then
    # Kill wlsunset using the PID from the file
    kill -TERM $(cat "$PID_FILE")
    echo "wlsunset stopped."
    # Remove the PID file
    rm "$PID_FILE"
else
    # Start wlsunset and save its PID to the file
    wlsunset -t 4000 -T 4500 -s 18:00 -S 06:00 -d 1800 -g 0.9 &
    echo $! > "$PID_FILE"
    echo "wlsunset started."
fi
